# Exported from Render on 2024-08-23T03:52:51Z
services:
- type: web
  name: testbox
  runtime: python
  repo: https://github.com/liuwenhua008/testbox
  plan: free
  envVars:
  - key: RENDER_NAME
    sync: false
  - key: BOT_TOKEN
    sync: false
  region: singapore
  buildCommand: pip install -r requirements.txt
  startCommand: python main.py
version: "1"
